name = "LatticeStats"
uuid = "2cfdc071-5958-49b7-826d-de4dbe5e0b3b"
authors = ["hershsingh <hersh@phy.duke.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
